# NOTE version 2.1 should be used in order to support used orbs 
version: 2.1

# TODO add the orb to handle AWS deployment ? aws-ecs? 
# TODO try to use sh instead of compare-url orb
orbs:
  slack: circleci/slack@3.3.0
  circle-compare-url: iynere/compare-url@1.1.0

# Note: CircleCI occasionally makes scheduled changes to images to fix bugs or otherwise improve functionality, 
# and these changes can sometimes cause affect how images work in CircleCI jobs. 
# Please follow the convenience-images tag on Discuss to be notified in advance of scheduled maintenance.

# TODO We can create our oun image to speed up builds
# https://circleci.com/docs/2.0/private-images/
# Here I use image from https://hub.docker.com/r/circleci/node/, with an appropriate docker version

executors:
  executor1:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers

workflows:
  version: 2
  main:
    jobs:
      - detect
      # - build

      # - dev-release:
      #     context: app-publishing
      #     requires:
      #       - lint
      #       - build

      # - trigger-downstream:
      #     context: orb-publishing
      #     requires:
      #       - dev-release
      #     filters:
      #       branches:
      #         only: master

      # - hold:
      #     type: approval
      #     requires:
      #       - trigger-downstream
      #     filters:
      #       branches:
      #         only: master

jobs:
  detect:
    executor: executor1
    steps:
      - checkout
      - run: 
          name: Detecting changed sub-repositories to trigger builds
          command: |
            echo -e "Detecting changed sub-repositories to trigger builds\n"
  # build:
  #   working_directory: ~/repo

  #   steps:
  #     # pre-defined command, reserved word
  #     - checkout
  #     # TODO configure cache
  #     # Download and cache dependencies ? 
  #     # TODO we should handle app-specific package.json
  #     - restore_cache:
  #         keys:
  #           - v1-dependencies-{{ checksum "package.json" }}
  #           # fallback to using the latest cache if no exact match is found
  #           - v1-dependencies-

  #     - run: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}
# TODO Detect of rilter branch (maybe filter jobs in workflow)
# TODO Implement all the steps which we have in Jenkins plus approval step and slack notifications 
